tosca_definitions_version: cloudify_dsl_1_3

description: >
  This Blueprint installs registrator on a Docker host

imports:
  - http://www.getcloudify.org/spec/cloudify/3.4/types.yaml
  - {{ ONAPTEMPLATE_RAWREPOURL_org_onap_dcaegen2 }}/type_files/docker/2.3.0/node-type.yaml
  - {{ ONAPTEMPLATE_RAWREPOURL_org_onap_dcaegen2 }}/type_files/relationship/1.0.0/node-type.yaml

inputs:
  registrator-image:
    type: string
  external_ip:
    type: string

node_templates:

  registrator:
    type: dcae.nodes.DockerContainer
    properties:
        name:
            'test-registrator'
        image: { get_input : registrator-image }
    relationships:
      - type: dcae.relationships.component_contained_in
        target: docker_host
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          inputs:
            envs:
              EXTERNAL_IP: { get_input : external_ip }
            volumes:
              - host:
                  path: '/var/run/docker.sock'
                container:
                  bind: '/tmp/docker.sock'
                  mode: 'ro'
  
  docker_host:
    type: dcae.nodes.SelectedDockerHost
    properties:
        location_id:
          'rework-central'
        docker_host_override:
          'platform_dockerhost'
